// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'DefaultFirebaseOptions have not been configured for web - '
        'you can reconfigure this by running the FlutterFire CLI again.',
      );
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        return android;
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDNyIk1lK9Op6Q6OCsZQ2juX0Fc3Aju-F8',
    appId: '1:426794987394:android:58c9ac65cd0a09f85da99b',
    messagingSenderId: '426794987394',
    projectId: 'streakup-habits',
    storageBucket: 'streakup-habits.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAgjIJxk-OLFMG_mrO3xjORnqdAj2vqLhI',
    appId: '1:426794987394:ios:53e38df90206851c5da99b',
    messagingSenderId: '426794987394',
    projectId: 'streakup-habits',
    storageBucket: 'streakup-habits.firebasestorage.app',
    iosBundleId: 'com.streakup.streakup',
    iosClientId: '426794987394-4a8pn6bs3ohgooqtj7gh25nenc7hl8r4.apps.googleusercontent.com',
  );
}
